kind = "web"
previewPath = "/"
title = "LilosCandle"
version = "1.0.0"
id = "artifacts/liloscandle"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
localPort = 21532
name = "web"
paths = ["/"]

[services.development]
run = "pnpm --filter @workspace/liloscandle run dev"

[services.env]
PORT = "21532"
BASE_PATH = "/"

[services.production]
build = ["pnpm", "--filter", "@workspace/liloscandle", "run", "build"]
publicDir = "artifacts/liloscandle/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"
