[[pages]]
path = "/"
screenshotTimestamp = "2026-03-11T17:25:35Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/e4785bd6-e041-4531-9ca1-19964df3ecb1/61f51fc4-35cd-46fd-8d74-9f32d196ae25/eaWluc8"
